<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">

    <title>Employment Offer Letter</title>

    <style>

        body {
            font-family: DejaVu Sans, sans-serif;
            color: #1e293b;
            line-height: 1.6;
            font-size: 13px;
            margin: 45px;
        }

        .header {
            border-bottom: 2px solid #4f46e5;
            padding-bottom: 18px;
            margin-bottom: 35px;
        }

        .company {
            font-size: 24px;
            font-weight: bold;
            color: #4f46e5;
        }

        .title {
            text-align: center;
            margin: 35px 0;
            font-size: 22px;
            font-weight: bold;
        }

        .section {
            margin-top: 25px;
        }

        .label {
            font-weight: bold;
        }

        .details {
            margin-top: 15px;
            padding: 18px;
            border: 1px solid #e2e8f0;
            background: #f8fafc;
        }

        .footer {
            margin-top: 60px;
            border-top: 1px solid #e2e8f0;
            padding-top: 20px;
            font-size: 11px;
            color: #64748b;
        }

    </style>

</head>


<body>

    {{-- Header --}}

    <div class="header">

        <div class="company">
            {{ $offer->application->job->company }}
        </div>

        <div>
            Employment Offer
        </div>

    </div>


    {{-- Date --}}

    <p>
        <strong>Date:</strong>
        {{ now()->format('d M Y') }}
    </p>


    {{-- Candidate --}}

    <p>
        Dear
        <strong>
            {{ $offer->application->user->name }}
        </strong>,
    </p>


    {{-- Introduction --}}

    <p>

        We are pleased to offer you the position of

        <strong>
            {{ $offer->application->job->title }}
        </strong>

        at

        <strong>
            {{ $offer->application->job->company }}
        </strong>.

    </p>


    {{-- Offer Details --}}

    <div class="section">

        <h3>
            Offer Details
        </h3>


        <div class="details">

            <p>
                <span class="label">
                    Position:
                </span>

                {{ $offer->application->job->title }}
            </p>


            <p>
                <span class="label">
                    Company:
                </span>

                {{ $offer->application->job->company }}
            </p>


            <p>
                <span class="label">
                    Annual Compensation:
                </span>

                ₹{{ number_format($offer->salary, 2) }}
            </p>


            <p>
                <span class="label">
                    Joining Date:
                </span>

                {{ $offer->joining_date->format('d M Y') }}
            </p>


            @if($offer->offer_expiry_date)

                <p>

                    <span class="label">
                        Offer Valid Until:
                    </span>

                    {{ $offer->offer_expiry_date->format('d M Y') }}

                </p>

            @endif

        </div>

    </div>


    {{-- Responsibilities --}}

    <div class="section">

        <h3>
            Employment Terms
        </h3>

        <p>

            Your employment will be subject to the company's
            policies, procedures, and applicable terms of employment.

            Further details regarding your responsibilities,
            working arrangements, and employment conditions will
            be communicated during the onboarding process.

        </p>

    </div>


    {{-- Notes --}}

    @if($offer->notes)

        <div class="section">

            <h3>
                Additional Information
            </h3>

            <p>
                {{ $offer->notes }}
            </p>

        </div>

    @endif


    {{-- Closing --}}

    <div class="section">

        <p>

            We look forward to welcoming you to the team.

        </p>


        <p>

            Please review this offer carefully and respond within
            the validity period mentioned above.

        </p>

    </div>


    {{-- Signature --}}

    <div style="margin-top:50px;">

        <p>
            Regards,
        </p>

        <p>
            <strong>
                Recruitment Team
            </strong>
        </p>

        <p>
            {{ $offer->application->job->company }}
        </p>

    </div>


    {{-- Footer --}}

    <div class="footer">

        This document is an employment offer generated by
        {{ $offer->application->job->company }}.

    </div>

</body>

</html>